### ISSUE TITLE
Erläuterung von MQTT 

### ISSUE THREAD

**Issue by murmeltier08** [rancilio-pid/ranciliopid-handbook#11]
MQTT erläutern im Handbuch

**Comment by rasimriver** [comment]
Erste Schritte gab es bereits: [Link](https://github.com/rancilio-pid/ranciliopid-handbook/blob/main/de/customization/mqtt.md) - falls jemand helfen mag :)

**Comment by rasimriver** [comment]
Vermutlich reichen die vorhandenen Infos, wenn bis heute keine Anpassung erforderlich war.
