### ISSUE TITLE
Electric circuit(s) as original image(s)

### ISSUE THREAD

**Issue by P1Rebo** [rancilio-pid/ranciliopid-handbook#13]
First of all, thank you very much for all the time and effort invested!

Question:
Would it be possible to provide the original images of the latest scheme in parallel to the jpg exports? 

Background info:
I'm asking because I have a PID circuit installed since 1 year now and want to switch to the "full version". But I'l like to kick out the power button and install the display in this place (Rancilio power supply is switched by my home automation / power relais).

Thanks in advance!
Pedro

**Comment by rasimriver** [comment]
Hi @P1Rebo being afraid, that your issue is already solved (sorry about the late reply), I am still curious how the solution could possibly look like. You are mainly requesting the source files of this site: [Link](https://manual.rancilio-pid.de/de/hardware/schaltplaene.html)?

**Comment by P1Rebo** [comment]
Sorry for my late reply. Exactly this was the solution I had in mind :-)
