### ISSUE TITLE
PID Kaltstart andere Funktion

### ISSUE THREAD

**Issue by murmeltier08** [rancilio-pid/ranciliopid-handbook#39]
PID Kaltstart ergänzen: Anderes Verhalten vom PID

**Comment by rasimriver** [comment]
Reicht das nicht: [Link](https://manual.rancilio-pid.de/de/customization/pid-werte.html#kaltstart)?

**Comment by LoQue90** [comment]
da sich der Kaltstart eh nochmal geändert hat und auch nicht mehr standardmäßig mit PoM läuft, wohl inzwischen obsolet, oder?
