### ISSUE TITLE
Homebrew package name is different

### ISSUE THREAD

**Issue by kjyv** [rancilio-pid/ranciliopid-handbook#43]
The documentation should suggest `brew install visual-studio-code` ;) 
(See [Formula](https://formulae.brew.sh/cask/visual-studio-code))

Additionally, PlatformIO can also directly be installed with `brew install platformio`

**Comment by LoQue90** [comment]
fixed with https://github.com/rancilio-pid/ranciliopid-handbook/commit/f81913331d832c762a160d4e4034c83e347725ff
