### ISSUE TITLE
userConfig script also usable on macOS

### ISSUE THREAD

**Issue by kjyv** [rancilio-pid/ranciliopid-handbook#44]
"Für Linux-Nutzer haben wir in rancilio-pid/scripts/create_user_config.sh ein Skript abgelegt"
-> The script is also prepared for macOS so that could be included

**Comment by LoQue90** [comment]
i could not find where this is in the manual

**Comment by kjyv** [comment]
Well, since the 1.5 years it was probably removed sometime. I guess we can close this :)
