### ISSUE TITLE
Brew detection page connecting wrong voltage to ESP

### ISSUE THREAD

**Issue by kjyv** [rancilio-pid/ranciliopid-handbook#47]
Unter https://manual.rancilio-pid.de/de/customization/brueherkennung.html (Details foldout) wird ein Verbindungsschema angegeben, bei dem 5V mit dem Optokoppler verbunden werden. Diese werden dann im Fall, dass der Brühschalter angeschaltet ist, an den ESP-Pin durchgeschaltet. Die Pins dürfen aber nur mit max 3,6V beschaltet werden und werden so u.U. beschädigt. Ich denke es sollte dort 3V3 stehen, nicht 5V.

**Comment by murmeltier08** [comment]
behoben
