### ISSUE TITLE
PCB Bestellinfos kaputt

### ISSUE THREAD

**Issue by jan--f** [rancilio-pid/ranciliopid-handbook#73]
Hallo, in der Bestellliste (und an andere Stellen) ist ein Discordinvite Link, der leider nicht funktioniert.
![2024-01-30-141415_555x401](https://github.com/rancilio-pid/ranciliopid-handbook/assets/458501/aef6518d-2193-40f6-a53a-7e85206c007e)

Ohne Account kann man leider auch keinen Kontakt aufnehmen und dazu scheint Discord derzeit keinen neuen Accounts ausgeben zu wollen. Ich habe jedenfalls bisher nach mehreren Versuchen noch keine Bestätigungsmail bekommen. 

Eine Alternative wäre sehr willkommen. Euer PCB sieht super aus und ich würde ich freuen es kaufen zu können.

**Comment by LoQue90** [comment]
Hey,

danke für den Hinweis, dann haben wir wohl noch nicht alle ausgetauscht.
Auf der Webseite findet sich ein funktionierender Link. Hier auch nochmal.
https://discord.com/invite/Kq5RFznuU4
Das Discord keine Konten mehr ausgibt ist mir neu, vielleicht deinerseits Spamfilter oder bei Discord klemmt etwas.

**Comment by LoQue90** [comment]
Der Link in der Bestellliste bringt mich auf unsere CleverCoffee Discord. Kann dein Problem daher nicht nachvollziehen.

**Comment by jan--f** [comment]
Danke! Da wohl nur zwischenzeitlich was faul bei Discord.
